### ISSUE TITLE
Put the Pile Button to the Adressbar

### ISSUE THREAD

**Issue by Teyro** [arminbw/pile#2]
Hi there,

I miss a space safeing feature to put the "Add to Pile" Button to the Adressbar? Is it possible to add this to the addon? Like this? https://cloud.teyro.tech/index.php/s/WzmqK61pbLYrkA3

Best wishes!
Chris

**Comment by arminbw** [comment]
Hi Chris! I don't think there is much space gained, if the button wanders from the the navbar into the address bar (you can resize the address bar), but I gave it a thought: Thing is, the Pocket and bookmarking buttons in the address bar are toggle buttons. So to keep the design consistent, the Pile button would have to behave the same way. This, again, would require the add-on to search all bookmarks every time a new page is loaded. It might not be a big thing for most users, but some may have rather large collections of bookmarks, and I would like to keep Pile as lightweight as possible - not only visually, but also performance-wise.
