### ISSUE TITLE
[Feature request] Top or bottom of the pile?

### ISSUE THREAD

**Issue by ineuw** [arminbw/pile#5]
Even though the extension is named "Pile", as in "Top of the Pile", would you please consider adding the option of placing the bookmarks at the "Bottom of the Pile" as well?

**Comment by arminbw** [comment]
I have to think about that. Apart from a configuration page, Pile would also need new visual feedback patterns.

**Comment by ineuw** [comment]
Thanks for the reply. I realize that it' must be a lot of work, so just consider it as a possibility in case you want to add a feature.

**Comment by arminbw** [comment]
I will do that… and thanks for the feedback.
