### ISSUE TITLE
Sidebar hotkey conflict on Windows

### ISSUE THREAD

**Issue by sotakal** [arminbw/pile#8]
Hi, love your minimalist addon, the only trouble is that on Windows, the default hotkey for showing the sidbar overlaps with showing History from Firefox's toolbar. Could we either have a different hotkey, have the hotkey configurable, or an alternative quick way to open the sidebar?

I can imagine that middle clicking the Pile icon on toolbar would open/close the sidebar list.

As for the new hotkey, Alt+Shift+O could work - it's right next to the P key, and would have O as in "open sidebar".

**Comment by arminbw** [comment]
@sotakal Firefox allows you to manage your keyboard shortcuts. The functionality is a bit hidden, though:
* go to `about/addons`
* click on `Extensions`
* click on the cogwheel icon (top right)
* choose `Manage Extension Shortcuts`

**Comment by sotakal** [comment]
Thanks for the tip, I wasn't aware of this. Resolved!
